<?php
return [
    '3do' => [
        'box',
        'case',
        'manual',
        'disc',
        'case_art',
        'insert',
    ],
    '3ds' => [
        'case',
        'manual',
        'cartridge',
        'case_art',
        'insert',
    ],
    'atari2600' => [
        'box',
        'manual',
        'cartridge',
        'insert',
    ],
    'atari5200' => [
        'box',
        'manual',
        'cartridge',
        'insert',
    ],
    'atari7800' => [
        'box',
        'manual',
        'cartridge',
        'insert',
    ],
    'CD-i' => [
        'box',
        'manual',
        'disc',
        'case',
        'case_art',
        'insert',
    ],
    'dc' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'gamegear' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'clamshell',
        'insert',
    ],
    'gb' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'gba' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'gbc' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'Jaguar' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'JaguarCD' => [
        'box',
        'manual',
        'disc',
        'case',
        'case_art',
        'insert',
    ],
    'Lynx' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'n64' => [
        'box',
        'manual',
        'cartridge',
        'styrofoam',
        'insert',
    ],
    'nds' => [
        'case',
        'manual',
        'cartridge',
        'case_art',
        'insert',
    ],
    'neogeoaes' => [
        'box',
        'manual',
        'cartridge',
        'insert',
    ],
    'neogeocd' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'neogeocolor' => [
        'box_or_case',
        'manual',
        'cartridge',
        'clamshell',
        'art_or_holder',
        'case_art',
        'insert',
    ],
    'nes' => [
        'box',
        'manual',
        'cartridge',
        'styrofoam',
        'insert',
    ],
    'ngage' => [
        'case',
        'manual',
        'cartridge',
        'case_art',
        'clamshell',
        'insert',
    ],
    'ngc' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'ps' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'ps2' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'ps3' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'ps4' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'psp' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'psvita' => [
        'cartridge',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'saturn' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'styrofoam',
        'insert',
    ],
    'sega32' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'segacd' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'styrofoam',
        'insert',
    ],
    'smd' => [
        'box_or_case',
        'manual',
        'cartridge',
        'art_or_holder',
        'insert',
    ],
    'sms' => [
        'case',
        'manual',
        'cartridge',
        'case_art',
        'insert',
    ],
    'snes' => [
        'box',
        'manual',
        'cartridge',
        'case',
        'case_sticker',
        'styrofoam',
        'insert',
    ],
    'switch' => [
        'case',
        'manual',
        'cartridge',
        'case_art',
        'insert',
    ],
    'turbografx16' => [
        'box',
        'manual',
        'cartridge',
        'case',
        'case_sticker',
        'styrofoam',
        'insert',
    ],
    'turbografx16cd' => [
        'box',
        'manual',
        'disc',
        'case',
        'case_art',
        'styrofoam',
        'insert',
    ],
    'virtualboy' => [
        'box',
        'manual',
        'cartridge',
        'cartridge_holder',
        'insert',
    ],
    'wii' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'wiiu' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'xbox' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'xbox360' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
    'xboxone' => [
        'disc',
        'manual',
        'case',
        'case_art',
        'insert',
    ],
];
